/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedListasIdRouteImport } from './routes/_authenticated/listas.$id'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin.areas'
import { Route as AuthenticatedListasIdItensItemIdRouteImport } from './routes/_authenticated/listas.$id.itens.$itemId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListasIdRoute = AuthenticatedListasIdRouteImport.update({
  id: '/listas/$id',
  path: '/listas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/admin/areas',
  path: '/admin/areas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListasIdItensItemIdRoute =
  AuthenticatedListasIdItensItemIdRouteImport.update({
    id: '/itens/$itemId',
    path: '/itens/$itemId',
    getParentRoute: () => AuthenticatedListasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/listas/$id': typeof AuthenticatedListasIdRouteWithChildren
  '/listas/$id/itens/$itemId': typeof AuthenticatedListasIdItensItemIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/listas/$id': typeof AuthenticatedListasIdRouteWithChildren
  '/listas/$id/itens/$itemId': typeof AuthenticatedListasIdItensItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/listas/$id': typeof AuthenticatedListasIdRouteWithChildren
  '/_authenticated/listas/$id/itens/$itemId': typeof AuthenticatedListasIdItensItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/areas'
    | '/listas/$id'
    | '/listas/$id/itens/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/admin/areas'
    | '/listas/$id'
    | '/listas/$id/itens/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/'
    | '/_authenticated/admin/areas'
    | '/_authenticated/listas/$id'
    | '/_authenticated/listas/$id/itens/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listas/$id': {
      id: '/_authenticated/listas/$id'
      path: '/listas/$id'
      fullPath: '/listas/$id'
      preLoaderRoute: typeof AuthenticatedListasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/admin/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listas/$id/itens/$itemId': {
      id: '/_authenticated/listas/$id/itens/$itemId'
      path: '/itens/$itemId'
      fullPath: '/listas/$id/itens/$itemId'
      preLoaderRoute: typeof AuthenticatedListasIdItensItemIdRouteImport
      parentRoute: typeof AuthenticatedListasIdRoute
    }
  }
}

interface AuthenticatedListasIdRouteChildren {
  AuthenticatedListasIdItensItemIdRoute: typeof AuthenticatedListasIdItensItemIdRoute
}

const AuthenticatedListasIdRouteChildren: AuthenticatedListasIdRouteChildren = {
  AuthenticatedListasIdItensItemIdRoute: AuthenticatedListasIdItensItemIdRoute,
}

const AuthenticatedListasIdRouteWithChildren =
  AuthenticatedListasIdRoute._addFileChildren(
    AuthenticatedListasIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedListasIdRoute: typeof AuthenticatedListasIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedListasIdRoute: AuthenticatedListasIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
